
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import static oracle.jrockit.jfr.events.Bits.intValue;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mat
 */
public class GUI_Partida extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    
    char[][] cWordsM;
    String[][] palavras;
    JTextField[][] campo; // Campo de quadrados
    JLabel[] idDica;
    JLabel[] lbDicas;
    JLabel boxDicas;
    double width;
    double height;
    
    public GUI_Partida() {
        initComponents();
        setFullScreen();
        this.setTitle("Partida");
        
        PalavrasCruzadas cWords = new PalavrasCruzadas();
        this.cWordsM = cWords.getCruzada();
        this.palavras = cWords.getPalavras();
        
        int altura = cWords.getAltura();
        int largura = cWords.getLargura();
        int distCentro = cWords.getDistCentro()+1;
        int[] qntEsq = cWords.getQntEsq();
        
        campo = new JTextField[altura][largura];
        idDica = new JLabel[altura+1];
        
        for(int i = 0; i < altura+1; i++)
        {
            System.out.println(i + ": " + palavras[i][1]);
            
            if(i == 0)
            {
                idDica[i] = new JLabel();
                idDica[i].setLocation((40*distCentro)-29, 10);
                idDica[i].setText("DICA");
                idDica[i].setFont(new Font("Courier New", Font.ITALIC, 12));
                idDica[i].setVisible(true);
                idDica[i].setSize(45, 30);
                idDica[i].setToolTipText(palavras[i][0]);
                this.add(idDica[i]);
            }
            else
            {
                idDica[i] = new JLabel();
                idDica[i].setLocation(((qntEsq[i-1]+1)*40)-25, (40*i)+2);
                idDica[i].setText("DICA");
                idDica[i].setFont(new Font("Courier New", Font.ITALIC, 12));
                idDica[i].setVisible(true);
                idDica[i].setSize(30, 30);
                idDica[i].setToolTipText(palavras[i][0]);
                this.add(idDica[i]);
            }
        }
        
        for(int i = 0, h = 40; i < altura; i++, h += 40)
            for(int j = 0, w = 10; j < largura; j++, w += 40)
                if(cWordsM[i][j] != '0')
                {
                    campo[i][j] = new JTextField();
                    campo[i][j].setLocation(w, h);
                    campo[i][j].setVisible(true);
                    campo[i][j].setSize(30, 30);
                    this.add(campo[i][j]);
                }
    }

    public void setFullScreen()
    {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.width = screenSize.getWidth();
        this.height = screenSize.getHeight();
        this.setSize((int)(long)Math.floor(width), (int)(long)Math.floor(height));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Partida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
