
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mat
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    
    char[][] cWordsM;
    String[][] palavras;
    JTextField[][] campo; // Campo de quadrados
    JLabel[] idxDica;
    
    public InterfaceGrafica() {
        initComponents();
        
        PalavrasCruzadas cWords = new PalavrasCruzadas();
        cWordsM = cWords.getCruzada();
        palavras = cWords.getPalavras();
        
        int altura = cWords.getAltura();
        int largura = cWords.getLargura();
        int distCentro = cWords.getDistCentro()+1;
        int[] qntEsq = cWords.getQntEsq();
        
        campo = new JTextField[altura][largura];
        idxDica = new JLabel[altura+1];
        
        for(int i = 0; i < altura+1; i++)
        {
            System.out.println(i + ": " + palavras[i][1]);
            
            if(i == 0)
            {
                idxDica[i] = new JLabel();
                idxDica[i].setLocation((40*distCentro)-20, 10);
                idxDica[i].setText(Integer.toString(i));
                idxDica[i].setVisible(true);
                idxDica[i].setSize(30, 30);
                idxDica[i].setToolTipText(palavras[i][0]);
                this.add(idxDica[i]);
            }
            else
            {
                idxDica[i] = new JLabel();
                idxDica[i].setLocation(((qntEsq[i-1]+1)*40), 40*i);
                idxDica[i].setText(Integer.toString(i));
                idxDica[i].setVisible(true);
                idxDica[i].setSize(30, 30);
                idxDica[i].setToolTipText(palavras[i][0]);
                this.add(idxDica[i]);
            }
        }
        
        for(int i = 0, h = 40; i < altura; i++, h += 40)
            for(int j = 0, w = 10; j < largura; j++, w += 40)
                if(cWordsM[i][j] != '0')
                {
                    campo[i][j] = new JTextField();
                    campo[i][j].setLocation(w, h);
                    campo[i][j].setVisible(true);
                    campo[i][j].setSize(30, 30);
                    this.add(campo[i][j]);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
